from typing import List, Dict, Set, Tuple, Any
from abc import abstractmethod
from .._a_platspec_cfgvalidator import _APlatSpecConfigValidator

from string_hasher import EHashingAlgorithm

from config_io.config_validator.exceptions import (
	InvalidConfigValueError,
	FieldDoesntExistsError,
	ConfigExtraFieldsError
)



class AGeneralConfigValidator(_APlatSpecConfigValidator):
	"""
		Represents an `IConfigValidator` for the configuration file that specifies the parameters common to the entire GenTestsAI software.
        
        The configuration file read is a dictionary containing:
		
			- "default_model_params" (Dict[str, Any]): Dictionary of default (fallback) parameters for LLMs. It contains:
            
                * "temperature" (float): The fallback value for the "Temperature" parameter
                * "gen_seed" (int): The fallback value for the generation seed
                * "top-k" (int): The fallback value for the "Top-K" parameter
                * "top-p" (float): The fallback value for the "Top-P" parameter
                * "context_window" (int): The fallback value for the context window size
                * "think" (bool): The fallback value specifying whether to use the model's thinking (if it has one)
                * The other keys depend on the specific inference platform to which this `IConfigValidator` relates
                
            - "max_gen_times" (int): Maximum number of attempts to generate a partial test suite
            - "max_corr_times" (int): Maximum number of attempts to correct a partial test suite
            - "model_names" (Dict[str, str]): Dictionary of parameters regarding the normalization of model names. Contains:
			
				* "hashing_alg" (str): The hashing algorithm to use for creating digests of LLM names
                * "digest_len" (int): The number of characters to use in the digests (the first `"digest_len"` characters)
			
			- "gen_tests_dir" (str): Name of the directory, within the Full Project Root Path, that will contain the tests generated by the LLMs
            - "skipped_tests" (Dict[str, str]): Dictionary of parameters regarding any skipped tests. It contains:
			
				* "file_format" (str): Format (e.g., JSON, XMLv2, YAML) of the skipped test files (in lowercase)
                * "funcs_gen" (str): Name of the file containing the list of functions skipped during generation
				* "meths_gen" (str): Name of the file listing the methods skipped during generation
                * "funcs_corr" (str): Name of the file listing the functions skipped during correction
                * "meths_corr" (str): Name of the file listing the methods skipped during correction
				
			- "always_excluded" (List[str]): The list of files or directories to be excluded from the entire GenTestsAI process
        
        and may optionally contain:
		
			- "response_fmt" (str): A Python RegEx pattern that identifies the response format. It must contain a named group called "gen_code"
        
        The specific inference platform is described by the descendants of this abstract class
	"""
	
	_ALL_FIELDS_NOPLAT: Set[str] = {
		"default_model_params",
		"max_gen_times", "max_corr_times",
		"model_names",
		"skipped_tests",
		"gen_tests_dir",
		"always_excluded"
	}
	_OPT_FIELDS: Set[str] = {
		"response_format"
	}
	_LLM_FIELDS: Set[str] = {
		"temperature", "gen_seed",
		"top-k", "top-p",
		"context_window",
		"think",
	}
	_LLMNAME_FIELDS: Set[str] = {
		"hashing_alg", "digest_len",
	}
	_SKIPD_FIELDS: Set[str] = {
		"file_format",
		"funcs_gen", "meths_gen",
		"funcs_corr", "meths_corr"
	}
	
	def __init__(
			self,
			config_dict: Dict[str, Any]
	):
		"""
			Creates a new AGeneralConfigValidator by providing it with the Python configuration dictionary
            that will be associated with this validator
            
            Parameters
            ----------
				config_dict: Dict[str, Any]
                    A mixed dictionary, indexed by strings, representing the read configuration file.
			
			Raises
            ------
                ValueError
                    Occurs if:
                    
                        - The provided dictionary has a value of `None`
                        - The provided dictionary is empty
		"""
		super().__init__(config_dict)
		
		
	def _ap__fields(self) -> Tuple[Set[str], Set[str]]:
		return (self._ALL_FIELDS_NOPLAT, self._OPT_FIELDS)
	
	
	def _ap__assert_mandatory(
			self,
			config_read: Dict[str, Any]
	):
		key: Any
		
		def_params: Any = config_read["default_model_params"]
		if not isinstance(def_params, dict):
			raise InvalidConfigValueError()
		for key in set(def_params.keys()):
			if not isinstance(key, str):
				raise InvalidConfigValueError()
		self._assert_llm_params(def_params)
		
		max_gens: int = config_read["max_gen_times"]
		max_corrs: int = config_read["max_corr_times"]
		gen_dirname: str = config_read["gen_tests_dir"]
		
		if (
				(not isinstance(max_gens, int)) or
				(not isinstance(max_corrs, int)) or
				(not isinstance(gen_dirname, str))
		):
			raise InvalidConfigValueError()
		if (
				(max_gens <= 0) or (max_corrs <= 0) or
				(gen_dirname == "")
		):
			raise InvalidConfigValueError()
		
		model_names: Dict[str, str] = config_read["model_names"]
		modelnames_fields = set(model_names.keys())
		if modelnames_fields < self._LLMNAME_FIELDS:
			raise FieldDoesntExistsError()
		if modelnames_fields > self._LLMNAME_FIELDS:
			raise ConfigExtraFieldsError()
		hashing_alg: str = model_names["hashing_alg"]
		try:
			EHashingAlgorithm[hashing_alg.upper().replace("-","_")]
		except KeyError:
			raise InvalidConfigValueError()
		
		skipd_tests: Dict[str, str] = config_read["skipped_tests"]
		if not isinstance(skipd_tests, dict):
			raise InvalidConfigValueError()
		self._assert_skipped_tests(skipd_tests)
		
		always_excl: List[str] = config_read["always_excluded"]
		if not isinstance(always_excl, list):
			raise InvalidConfigValueError()
		for elem in always_excl:
			if not isinstance(elem, str):
				raise InvalidConfigValueError()
	
	
	def _ap__assert_optional(self, config_read: Dict[str, Any]):
		response_fmt: str = config_read.get("response_fmt", None)
		if response_fmt is not None:
			if not isinstance(response_fmt, str):
				raise InvalidConfigValueError()
			
			if response_fmt.find("(?P<gen_code>") == -1:
				raise InvalidConfigValueError()
	
	
	def _ap__assert_purperrors(self, config_read: Dict[str, Any]):
		return
	
	
	##	============================================================
	##						ABSTRACT METHODS
	##	============================================================
	
	
	@abstractmethod
	def _ap__assert_platspec(self, config_read: Dict[str, Any]):
		pass
	
	
	##	============================================================
	##						PRIVATE METHODS
	##	============================================================


	@classmethod
	def _assert_llm_params(
			cls,
			llm_params: Dict[str, Any]
	):
		"""
			Checks the validity of the "default_model_params" field.
            
            If the check is successful, this operation is equivalent to a no-op.
            
            Raises
            ------
                InvalidConfigValueError
                    Occurs if the values of its fields are invalid
		"""
		llm_params_fields: Set[str] = set(llm_params.keys())
		if llm_params_fields < cls._LLM_FIELDS:
			raise InvalidConfigValueError()
		
		ctx_window: int = llm_params["context_window"]
		temp: float = llm_params["temperature"]
		top_k: int = llm_params["top-k"]
		top_p: float = llm_params["top-p"]
		gen_seed: int = llm_params["gen_seed"]
		think: bool = llm_params["think"]
		
		if (
				(not isinstance(ctx_window, int)) or
				(not isinstance(temp, float)) or
				(not isinstance(top_k, int)) or
				(not isinstance(top_p, float)) or
				(not isinstance(gen_seed, int)) or
				(not isinstance(think, bool))
		):
			raise InvalidConfigValueError()
		if (
				(ctx_window <= 0) or (top_k <= 0) or
				(gen_seed < 0) or
				(not (0.0 <= top_p <= 1.0)) or
				(not (0.0 <= temp <= 1.0))
		):
			raise InvalidConfigValueError()
		

	@classmethod
	def _assert_skipped_tests(
			cls,
			skipd_tests: Dict[str, str]
	):
		"""
			Checks the validity of the "skipped_tests" field.
            
            If the check succeeds, this operation is equivalent to a no-op.
            
            Raises
            ------
                ConfigExtraFieldsError
                    Occurs if the field format is invalid
		"""
		for key, value in skipd_tests.items():
			if not isinstance(key, str) or not isinstance(value, str):
				raise InvalidConfigValueError()
		
		if set(skipd_tests.keys()) != cls._SKIPD_FIELDS:
			raise InvalidConfigValueError()