from ollama_temperature_id import OllamaTemperatureHyperParamId
from ollama_topp_id import OllamaTopPHyperParamId
from ollama_topk_id import OllamaTopKHyperParamId

from ollama_numctx_id import OllamaNumCtxHyperParamId
from ollama_numpredict_id import OllamaNumPredictHyperParamId
from ollama_seed_id import OllamaSeedHyperParamId

from ollama_think_id import OllamaThinkHyperParamId