site_name: Documentation
site_description: GenTestsAI's Documentation
site_author: Filippo Mecozzi (codesavant23)

theme:
  name: material
  language: en
  logo: assets/gtsai_logoart.png
  favicon: assets/favicon.png
  custom_dir: overrides
  
  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode  
  
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
        
        
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16


  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy


nav:
  - Home: index.md
  - GenTestsAILib:
    - Introduction: gtsai_lib/intro.md
    - Architecture Overview: gtsai_lib/arch.md
    - User Manual:
        - Logical units variability: gtsai_lib/logical_units.md
    - Hierarchies (by scope):
        - Configuration:
            - ConfigParser:
                - IConfigParser: out/interfaces/IConfigParser.md
            - ConfigValidator:
                - IConfigValidator: out/interfaces/IConfigValidator.md
                - AGeneralConfigValidator: out/absclasses/AGeneralConfigValidator.md
                - AModelsConfigValidator: out/absclasses/AModelsConfigValidator.md
                - AAccessorConfigValidator: out/absclasses/AAccessorConfigValidator.md
  - TestGroup:
    - Test: out/test.md
    - TestAnn: out/test2.md
  - Setup:
    - Installazione: install.md
    - Configurazione: config.md


docs_dir: docs
site_dir: site


plugins:
  - search:
      lang: en
  - minify:
      minify_html: true


markdown_extensions:
  - admonition
  - codehilite
  - nl2br
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.details


copyright: Copyright &copy; 2026 - 2026 Filippo Mecozzi (codesavant23)


extra:
  pygments_style: default
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/codesavant23
  

extra_css:
  - styles/palette.css
  - styles/text.css
  - styles/elements.css
  - styles/admons.css
  - styles/acc_badges.css
  - styles/404.css