site_name: Documentation
site_description: GenTestsAI's Documentation
site_url: https://codesavant23.github.io/gentestsai/
site_author: Filippo Mecozzi (codesavant23)

theme:
  name: material
  language: en
  logo: assets/gtsai_logoart.png
  favicon: assets/favicon.png
  custom_dir: overrides
  
  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode  
  
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
        
        
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16


  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy


nav:
  - Home: index.md
  - Common concepts:
    - Glossary: common/glossary.md
    - Projects conventions: common/proj_convs.md
    - Focal Environments: common/focal_envs.md
  - GenTestsAI:
    - Introduction to GenTestsAI: gtsai/intro.md
  - GenTestsAILib:
    - Introduction to GenTestsAILib: gtsai_lib/intro.md
    - Architecture overview: gtsai_lib/arch.md
    - Logical units variability: gtsai_lib/logical_units.md
    - Hierarchies (by scope):
      - Focal Environments:
        - Container Description File building:
          - IDockfBuilder: hiers/gtsai_lib/interfaces/IDockfBuilder.md
          - _ABaseDockfBuilder: hiers/gtsai_lib/absclasses/_ABaseDockfBuilder.md
          - ATransactDockfBuilder: hiers/gtsai_lib/absclasses/ATransactDockfBuilder.md
          - SimpleTransactDockfBuilder: hiers/gtsai_lib/classes/SimpleTransactDockfBuilder.md
          - Exceptions:
            - TransactionNotStartedError: hiers/gtsai_lib/classes/TransactionNotStartedError.md
            - TransactionStartedError: hiers/gtsai_lib/classes/TransactionStartedError.md

        - Configuring Focal Environments:
          - IFocalEnvConfigurator: hiers/gtsai_lib/interfaces/IFocalEnvConfigurator.md
          - _ABaseFocalEnvConfigurator: hiers/gtsai_lib/absclasses/_ABaseFocalEnvConfigurator.md
          - V1FocalEnvConfigurator: hiers/gtsai_lib/classes/V1FocalEnvConfigurator.md
          - Building cache cleaning:
            - IBuildCacheCleaner: hiers/gtsai_lib/interfaces/IBuildCacheCleaner.md
            - DockerBuildCacheCleaner: hiers/gtsai_lib/classes/DockerBuildCacheCleaner.md
            - PodmanGe400BuildCacheCleaner: hiers/gtsai_lib/classes/PodmanGe400BuildCacheCleaner.md
            - PodmanLt400BuildCacheCleaner: hiers/gtsai_lib/classes/PodmanLt400BuildCacheCleaner.md
            - BuildCacheCleanerFactory: hiers/gtsai_lib/classes/BuildCacheCleanerFactory.md
            - EContainerManager: hiers/gtsai_lib/enums/EContainerManager.md
          - Exceptions:
            - BaseImageNotSetError: hiers/gtsai_lib/classes/BaseImageNotSetError.md
            - DefaultPythonVersionNotSetError: hiers/gtsai_lib/classes/DefaultPythonVersionNotSetError.md

        - Focal Containers:
          - FocalContainer: hiers/gtsai_lib/classes/FocalContainer.md
          - Exceptions:
            - CommandNeverExecutedError: hiers/gtsai_lib/classes/CommandNeverExecutedError.md
            - ContainerAlreadyRunningError: hiers/gtsai_lib/classes/ContainerAlreadyRunningError.md
            - ContainerNotRunningError: hiers/gtsai_lib/classes/ContainerNotRunningError.md

      - Partial Test Suites:
        - Syntactic code check:
          - ISyntacticChecker: hiers/gtsai_lib/interfaces/ISyntacticChecker.md
          - _ABaseSyntacticChecker: hiers/gtsai_lib/absclasses/_ABaseSyntacticChecker.md
          - PyCompileSyntChecker: hiers/gtsai_lib/classes/PyCompileSyntChecker.md
          - SyntacticCheckerFactory: hiers/gtsai_lib/classes/SyntacticCheckerFactory.md
          - ESyntCheckerTool: hiers/gtsai_lib/enums/ESyntCheckerTool.md
        - Linting code check:
          - LintingChecker: hiers/gtsai_lib/classes/LintingChecker.md

        - Generation:
          - EntityPtsuiteGenerator: hiers/gtsai_lib/classes/EntityPtsuiteGenerator.md

        - Syntactic correction:
          - PtsuiteSyntacticCorrector: hiers/gtsai_lib/classes/PtsuiteSyntacticCorrector.md
          - Exceptions:
            - SourceMaterializationError: hiers/gtsai_lib/classes/SourceMaterializationError.md
            - SyntacticCheckError: hiers/gtsai_lib/classes/SyntacticCheckError.md
        - Linting correction:
          - PtsuiteLintingCorrector: hiers/gtsai_lib/classes/PtsuiteLintingCorrector.md
          - Exceptions:
            - SyntacticallyIncorrectPtsuiteError: hiers/gtsai_lib/classes/SyntacticallyIncorrectPtsuiteError.md

        - Exceptions:
          - PromptingSessionNotStartedError: hiers/gtsai_lib/classes/PromptingSessionNotStartedError.md
          - PromptingSessionInProgressError: hiers/gtsai_lib/classes/PromptingSessionInProgressError.md
          - PromptingSessionNeverPerformedError: hiers/gtsai_lib/classes/PromptingSessionNeverPerformedError.md
          - WrongResponseFormatError: hiers/gtsai_lib/classes/WrongResponseFormatError.md

        - Caching:
          - IPtsuiteCacheAccessor: hiers/gtsai_lib/interfaces/IPtsuiteCacheAccessor.md
          - _ABasePtsuiteCacheAccessor: hiers/gtsai_lib/absclasses/_ABasePtsuiteCacheAccessor.md
          - Sqlite3CacheAccessor: hiers/gtsai_lib/classes/Sqlite3CacheAccessor.md
          - PtsuiteCacheAccessorFactory: hiers/gtsai_lib/classes/PtsuiteCacheAccessorFactory.md
          - ECacheAccessorType: hiers/gtsai_lib/enums/ECacheAccessorType.md
          - Exceptions:
            - CacheFileTypeError: hiers/gtsai_lib/classes/CacheFileTypeError.md
            - EntryAlreadyExistsError: hiers/gtsai_lib/classes/EntryAlreadyExistsError.md
            - EntryNotExistsError: hiers/gtsai_lib/classes/EntryNotExistsError.md
            - ProjectSpaceNotExistsError: hiers/gtsai_lib/classes/ProjectSpaceNotExistsError.md
            - ProjectSpaceReservationError: hiers/gtsai_lib/classes/ProjectSpaceReservationError.md

        - Skipped Autonomous Entities:
          - ISkipWriter: hiers/gtsai_lib/interfaces/ISkipWriter.md
          - _ABaseSkipWriter: hiers/gtsai_lib/absclasses/_ABaseSkipWriter.md
          - JsonListSkipWriter: hiers/gtsai_lib/classes/JsonListSkipWriter.md
          - SkipWriterFactory: hiers/gtsai_lib/classes/SkipWriterFactory.md
          - ESkippedTestsFtypeFormat: hiers/gtsai_lib/enums/ESkippedTestsFtypeFormat.md
          - Exceptions:
            - InvalidSkippedTestsFileError: hiers/gtsai_lib/classes/InvalidSkippedTestsFileError.md

      - Specific Code Metrics calculation:
        - ECoverageReportType: hiers/gtsai_lib/enums/ECoverageReportType.md
        - Entity-by-Entity coverage aggregation:
          - ICoveragePyEbyeAggregator: hiers/gtsai_lib/interfaces/ICoveragePyEbyeAggregator.md
          - _ABaseCoverageEbyeAggregator: hiers/gtsai_lib/absclasses/_ABaseCoverageEbyeAggregator.md
          - JsonCoverageEbyeAggregator: hiers/gtsai_lib/classes/JsonCoverageEbyeAggregator.md
          - CoveragePyEbyeAggregatorFactory: hiers/gtsai_lib/classes/CoveragePyEbyeAggregatorFactory.md
          - Exceptions:
            - WrongReportTypeError: hiers/gtsai_lib/classes/WrongReportTypeError.md
        - Configuring coverage.py:
          - CoverageRcWriter: hiers/gtsai_lib/classes/CoverageRcWriter.md
          - Exceptions:
            - DataFileNotSetError: hiers/gtsai_lib/classes/DataFileNotSetError.md
            - ReportTypeNotSetError: hiers/gtsai_lib/classes/ReportTypeNotSetError.md

      - Utilities:
        - PromptBuilder: hiers/gtsai_lib/classes/PromptBuilder.md
        - Exceptions:
          - IncompletePromptError: hiers/gtsai_lib/classes/IncompletePromptError.md
          - InvalidPlaceholderError: hiers/gtsai_lib/classes/InvalidPlaceholderError.md
          - TemplateNotSetError: hiers/gtsai_lib/classes/TemplateNotSetError.md

      - Exceptions:
        - FocalProjectNotSetError: hiers/gtsai_lib/classes/FocalProjectNotSetError.md


docs_dir: docs
site_dir: site


plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - glightbox


markdown_extensions:
  - admonition
  - codehilite
  - nl2br
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true


copyright: Copyright &copy; 2026 - 2026 Filippo Mecozzi (codesavant23)


extra:
  pygments_style: default
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/codesavant23
  
extra_css:
  - styles/palette.css
  - styles/text.css
  - styles/elements.css
  - styles/admons.css
  - styles/ref_highlight.css
  - styles/acc_badges.css
  - styles/404.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  
extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js